# Generated by Django 6.0.4 on 2026-05-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('logo_emoji', models.CharField(default='🏢', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('exam_pattern', models.JSONField(blank=True, default=dict, help_text='JSON describing the exam structure, sections, and timing')),
                ('avg_package_lpa', models.DecimalField(blank=True, decimal_places=2, help_text='Average package in LPA', max_digits=5, null=True)),
                ('eligibility_criteria', models.TextField(blank=True)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('total_questions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
    ]
