# Generated by Django 6.0.4 on 2026-05-17 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('aptitude', 'Quantitative Aptitude'), ('reasoning', 'Logical Reasoning'), ('verbal', 'Verbal Ability'), ('di', 'Data Interpretation')], max_length=20)),
                ('icon', models.CharField(default='📝', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('text', models.TextField(help_text='Question text in English')),
                ('text_hi', models.TextField(blank=True, help_text='Question text in Hindi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('options', models.JSONField(help_text='List of options: [{"key":"A","text":"Option text","text_hi":"..."}]')),
                ('correct_option', models.CharField(max_length=1)),
                ('explanation', models.TextField(blank=True, help_text='Detailed explanation in English')),
                ('explanation_hi', models.TextField(blank=True, help_text='Explanation in Hindi')),
                ('shortcut_method', models.TextField(blank=True, help_text='Quick solving trick')),
                ('ai_explanation', models.TextField(blank=True, help_text='Cached AI-generated explanation')),
                ('source', models.CharField(blank=True, help_text='Where this question is from', max_length=200)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('times_attempted', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('elo_rating', models.FloatField(default=1200.0, help_text='Adaptive difficulty rating')),
                ('is_verified', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('companies', models.ManyToManyField(blank=True, related_name='questions', to='companies.company')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.topic')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['topic', 'difficulty'], name='questions_q_topic_i_2f996f_idx'), models.Index(fields=['elo_rating'], name='questions_q_elo_rat_08aad0_idx'), models.Index(fields=['difficulty', 'is_active'], name='questions_q_difficu_1254e3_idx')],
            },
        ),
    ]
