# Generated by Django 6.0.4 on 2026-05-17 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏅', max_length=10)),
                ('criteria_type', models.CharField(choices=[('questions_solved', 'Total Questions Solved'), ('streak_days', 'Streak Days'), ('test_score', 'Test Score Percentage'), ('tests_completed', 'Tests Completed'), ('topic_mastery', 'Topic Mastery'), ('xp_earned', 'XP Earned')], max_length=20)),
                ('criteria_value', models.IntegerField(help_text='Threshold value to earn this badge')),
                ('xp_reward', models.IntegerField(default=50, help_text='XP awarded when badge is earned')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['criteria_type', 'criteria_value'],
            },
        ),
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('bonus_xp', models.IntegerField(default=100)),
                ('questions', models.ManyToManyField(to='questions.question')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
